services:
  migrate-app:
    image: migrate/migrate
    container_name: "migrate-app"
    networks:
      - payment-processor-network
    volumes:
      - ./migrations/:/database
    environment:
      DATABASE_URI: ${DATABASE_URI:-postgresql://postgres:password@db:5432/postgres}
    command: ["-path", "/database", "-database", "${DATABASE_URI}", "up"]
    depends_on:
      db:
        condition: service_healthy
  app: 
    container_name: "payment-processor"
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - payment-processor-network
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URI: ${DATABASE_URI:-postgresql://postgres:password@db:5432/postgres}
      PORT: ${PORT:-3000}
      TEST_URL: ${TEST_URL:-http://localhost}

    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: postgres
    container_name: "payment-proccesor-db"
    restart: on-failure
    networks:
      - payment-processor-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
networks:
  payment-processor-network:
    driver: bridge
volumes:
  db-data: